# Generated by Django 5.1.3 on 2024-11-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signatures", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Signature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("signature", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="meritsheet",
            name="member",
        ),
        migrations.RemoveField(
            model_name="meritsheet",
            name="spreadsheet",
        ),
        migrations.RemoveField(
            model_name="meritsheet",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="meritsheet",
            name="active_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="meritsheet",
            name="brotherhood",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="meritsheet",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="meritsheet",
            name="initial",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="meritsheet",
            name="points",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="meritsheet",
            name="professional",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="Member",
        ),
    ]
