# Generated by Django 5.1.3 on 2024-11-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signatures", "0003_alter_meritsheet_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meritsheet",
            name="active_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="meritsheet",
            name="brotherhood",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="meritsheet",
            name="initial",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="meritsheet",
            name="points",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="meritsheet",
            name="professional",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
