# Generated by Django 5.1.3 on 2024-11-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signatures", "0004_alter_meritsheet_active_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meritsheet",
            name="points",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
